### PR TITLE
fixes #12: It will be better to restrict user to add either "user ID" or "name", without leaving both details empty 

### LINKED ISSUE #12: It will be better to restrict user to add either "user ID" or "name", without leaving both details empty
**Describe the bug**
At present, user is allowed to submit details without filling both user Id and name.It will be better to restrict user to add either "user ID" or "name", without leaving both empty.

**Screenshots**

ezgif com-video-to-gif(14)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by mustaqmustu**
Fixed #12

Screenshots of the change: 
image

### CODE REVIEW

File: TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java [hunk 1]
```diff
@@ -95,16 +95,21 @@ public void onClick(View v) {
...
                 id = id + uid1ET.getText().toString();
                 name = nameET.getText().toString();
-                if (flag == 1) {
-                    poojaTyp = String.valueOf(poojaType.getSelectedItem());
-
-                    overall = poojaTyp + getResources().getString(R.string.empty) + name + getResources().getString(R.string.empty) + paidCheck;
-                } else {
-                    money = moneyDonated.getText().toString();
-                    overall = money + getResources().getString(R.string.empty) + name + getResources().getString(R.string.empty) + paidCheck;
+                if (id.length() == 0) {
```
Comment (yashk2000) [inline TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java]: Check for length >= 3.

File: TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java [hunk 2]
```diff
@@ -95,16 +95,21 @@ public void onClick(View v) {
...
                 id = id + uid1ET.getText().toString();
                 name = nameET.getText().toString();
-                if (flag == 1) {
-                    poojaTyp = String.valueOf(poojaType.getSelectedItem());
-
-                    overall = poojaTyp + getResources().getString(R.string.empty) + name + getResources().getString(R.string.empty) + paidCheck;
-                } else {
-                    money = moneyDonated.getText().toString();
-                    overall = money + getResources().getString(R.string.empty) + name + getResources().getString(R.string.empty) + paidCheck;
+                if (id.length() == 3) {
```
Comment (yashk2000) [inline TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java]: `id.length() >=3`

Comment (yashk2000) [reply TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java]: It won't accept length > 3, please change than.

Comment (mustaqmustu) [reply TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java]: no @yashk2000 ...actual length of id is 3..i.e if nothing is entered..id length will be 3,then it wont allows the user...so if anything is entered,it will be greater than 3 and it allows the user.

Comment (yashk2000) [reply TempleApp/src/main/java/example/TempleApp/Activities/InsertData.java]: In that case it's fine :+1:

**Comment by vchrombie** [comment]
Looks everyone is satisfied with the work. Thanks, @mustaqmustu :smile:
