### PR TITLE
fix: Edited the toast messages in the search section

### LINKED ISSUE #90: Edit toast messages in Search section
**Describe the bug**
When user clicks on "people who registered "in search section, wrong toast is appearing as"Selected to register pooja". It is repeating with "People who Donated money".

**Expected behavior**
A clear toast message.

**Screenshots**
image
image

**Would you like to work on the issue?** (Yes/No)
No.

### PR DESCRIPTION
**Pull request by gopikaharikumar**
Fixed #90 

Edited the toast messages in the search section

### CODE REVIEW

File: app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java [hunk 1]
```diff
@@ -50,14 +50,14 @@ public void radioGroup(RadioGroup group, int checkedId) {
                 case R.id.radio_donate:
                     binding.totalView.setVisibility(View.VISIBLE);
                     flag = 0;
-                    Toast.makeText(getBaseContext(), getString(R.string.selected_donate), Toast.LENGTH_SHORT)
+                    Toast.makeText(getBaseContext(), getResources().getString(R.string.search_donations), Toast.LENGTH_SHORT)
```
Comment (yashk2000) [inline app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java]: Is `getResources() ` really needed? Will it not work without `getResources()`

Comment (gopikaharikumar) [reply app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java]: Will remove it
